=== younesyu/M1_DPR/Projet/master.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT p           (#PCDATA|p|ul|li|b|i|t)* >
<!ELEMENT ul           (#PCDATA|p|ul|li|b|i|t)* >
<!ELEMENT li           (#PCDATA|p|ul|li|b|i|t)* >
<!ELEMENT b          (#PCDATA|p|ul|li|b|i|t)* >
<!ELEMENT i           (#PCDATA|p|ul|li|b|i|t)* >
<!ELEMENT t           (#PCDATA|p|ul|li|b|i|t)* >
<!ELEMENT ol           (#PCDATA|p|ul|li|b|i|t)* >

<!ENTITY campus "Luminy">
<!ENTITY campus2 "Saint-Jerome">

<!ENTITY ueObligatoire "Obligatoire">
<!ENTITY ueOptionnelle "Option">

<!ENTITY % id 
          "id ID #REQUIRED">

<!ENTITY % ref 
          "ref IDREF #REQUIRED">

<!ELEMENT master        (intervenant*, parcours*, semestre*, unite*)>
<!ATTLIST master xmlns:xsi CDATA #IMPLIED 
					xsi:noNamespaceSchemaLocation CDATA #IMPLIED >

<!ELEMENT parcours         (nom, responsable+, description, debouche*, ref-semestre*)>
<!ELEMENT responsable           EMPTY>
<!ATTLIST responsable %ref;>
<!ELEMENT debouche           (#PCDATA)>
<!ELEMENT description           (#PCDATA|p|ul|li|b|i|t|ol)* >
<!ELEMENT ref-semestre EMPTY>
<!ATTLIST ref-semestre ref IDREF #REQUIRED>

<!ELEMENT semestre         (bloc-unite*) >
<!ELEMENT bloc-unite (ref-unite, role)>
<!ELEMENT ref-unite EMPTY>
<!ELEMENT role  (#PCDATA)>
<!ATTLIST ref-unite %ref;>
<!ATTLIST semestre %id;>

<!ELEMENT unite         (nom, credit, resume, plan, lieu*, ref-intervenant*)>
<!ATTLIST unite %id;>
<!ELEMENT nom           (#PCDATA)>
<!ELEMENT credit        (#PCDATA)>
<!ELEMENT resume        (#PCDATA|p|ul|li|b|i|t|ol)* >
<!ELEMENT plan          (#PCDATA|p|ul|li|b|i|t|ol)*>
<!ELEMENT lieu          (#PCDATA)>
<!ELEMENT ref-intervenant EMPTY>
<!ATTLIST ref-intervenant %ref;>

<!ELEMENT intervenant       (nom, mail, site)>
<!ATTLIST intervenant %id;>

<!ELEMENT mail      (#PCDATA)>
<!ELEMENT site      (#PCDATA)>

<!ELEMENT chapitre      (#PCDATA)>

=== younesyu/M1_DPR/Projet/master.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE master SYSTEM "master.dtd">

<master xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  	xsi:noNamespaceSchemaLocation="master.xsd" >

<intervenant id="II1000">
   <nom>ARTIÈRES Thierry</nom>
   <mail>thierry.artieres@lif.univ-mrs.fr</mail>
</intervenant>
<intervenant id="IN1021">
   <nom>BERTOLISSI Clara</nom>
   <mail>clara.bertolissi@univ-amu.fr</mail>
</intervenant>
<intervenant id="IN10388">
   <nom>FAVRE Benoit</nom>
   <mail>benoit.favre@univ-amu.fr</mail>
</intervenant>
<intervenant id="IN12068">
   <nom>HABET Djamal</nom>
   <mail>djamal.habet@univ-amu.fr</mail>
</intervenant>
<intervenant id="IN12141">
   <nom>JEGOU Philippe</nom>
   <mail>philippe.jegou@univ-amu.fr</mail>
</intervenant>
<intervenant id="IN12292">
   <nom>TERRIOUX Cyril</nom>
   <mail>cyril.terrioux@univ-amu.fr</mail>
</intervenant>
<intervenant id="IN12507">
   <nom>HAMRI Maamar El amine</nom>
   <mail>amine.hamri@univ-amu.fr</mail>
</intervenant>
<intervenant id="IN12544">
   <nom>BOUCELMA Omar</nom>
   <mail>omar.boucelma@univ-amu.fr</mail>
</intervenant>
<intervenant id="IN1262">
   <nom>CAPPONI Cecile</nom>
   <mail>cecile.capponi@univ-amu.fr</mail>
</intervenant>
<intervenant id="IN12883">
   <nom>FOURNIER Sebastien</nom>
   <mail>sebastien.fournier@univ-amu.fr</mail>
</intervenant>
<intervenant id="IN12969">
   <nom>RENE CHABAROT Lydie</nom>
   <mail>lydie.rene@univ-amu.fr</mail>
</intervenant>
<intervenant id="IN14003">
   <nom>DUPE Francois Xavier</nom>
   <mail>francois-xavier.dupe@univ-amu.fr</mail>
</intervenant>
<intervenant id="IN14758">
   <nom>BROCHE Martine</nom>
   <mail>martine.broche@univ-amu.fr</mail>
</intervenant>
<intervenant id="IN16208">
   <nom>COUETOUX Basile</nom>
   <mail>basile.couetoux@univ-amu.fr</mail>
</intervenant>
<intervenant id="IN16625">
   <nom>SELLAMI Sana</nom>
   <mail>sana.sellami@univ-amu.fr</mail>
</intervenant>
<intervenant id="IN18">
   <nom>MASSAT Jean Luc</nom>
   <mail>jean-luc.massat@univ-amu.fr</mail>
</intervenant>
<intervenant id="IN19444">
   <nom>KADRI Hachem</nom>
   <mail>hachem.kadri@univ-amu.fr</mail>
</intervenant>
<intervenant id="IN21048">
   <nom>RAMISCH Carlos</nom>
   <mail>carlos.ramisch@univ-amu.fr</mail>
</intervenant>
<intervenant id="IN2301">
   <nom>HUBERT Florence</nom>
   <mail>florence.hubert@univ-amu.fr</mail>
</intervenant>
<intervenant id="IN23202">
   <nom>ARRIGHI Pablo</nom>
   <mail>pablo.arrighi@univ-amu.fr</mail>
</intervenant>
<intervenant id="IN23203">
   <nom>PERROT Kevin</nom>
   <mail>kevin.perrot@univ-amu.fr</mail>
</intervenant>
<intervenant id="IN25554">
   <nom>MONMEGE Benjamin</nom>
   <mail>benjamin.monmege@univ-amu.fr</mail>
</intervenant>
<intervenant id="IN25567">
   <nom>CONTENSIN Magali</nom>
   <mail>magali.contensin@univ-amu.fr</mail>
</intervenant>
<intervenant id="IN2563">
   <nom>GODARD Emmanuel</nom>
   <mail>emmanuel.godard@univ-amu.fr</mail>
</intervenant>
<intervenant id="IN3524">
   <nom>LUGIEZ Denis</nom>
   <mail>denis.lugiez@univ-amu.fr</mail>
</intervenant>
<intervenant id="IN36256">
   <nom>VILLEVALOIS Didier</nom>
   <mail>didier.villevalois@univ-amu.fr</mail>
</intervenant>
<intervenant id="IN37076">
   <nom>HOAREAU Nicolas</nom>
   <mail>nicolas.hoareau@univ-amu.fr</mail>
</intervenant>
<intervenant id="IN37097">
   <nom>ROMANO Christian</nom>
   <mail>christian.romano@univ-amu.fr</mail>
</intervenant>
<intervenant id="IN37426">
   <nom>JULLIEN Christophe</nom>
   <mail>christophe.jullien@univ-amu.fr</mail>
</intervenant>
<intervenant id="IN37528">
   <nom>DI MOLFETTA Giuseppe</nom>
   <mail>giuseppe.di-molfetta@univ-amu.fr</mail>
</intervenant>
<intervenant id="IN38232">
   <nom>IMBS Damien</nom>
   <mail>damien.imbs@univ-amu.fr</mail>
</intervenant>
<intervenant id="IN4595">
   <nom>REYNIER Pierre-Alain</nom>
   <mail>pierre-alain.reynier@univ-amu.fr</mail>
</intervenant>
<intervenant id="IN4718">
   <nom>EYRAUD Remi</nom>
   <mail>remi.eyraud@univ-amu.fr</mail>
</intervenant>
<intervenant id="IN4872">
   <nom>RAFFIN Romain</nom>
   <mail>romain.raffin@univ-amu.fr</mail>
</intervenant>
<intervenant id="IN4955">
   <nom>SANTOCANALE Luigi</nom>
   <mail>luigi.santocanale@univ-amu.fr</mail>
</intervenant>
<intervenant id="IN616">
   <nom>AGOPIAN Roland</nom>
   <mail>roland.agopian@univ-amu.fr</mail>
</intervenant>
<intervenant id="IN7566">
   <nom>CEPOI Victor</nom>
   <mail>victor.cepoi@univ-amu.fr</mail>
</intervenant>
<intervenant id="IN7574">
   <nom>SEQUEIRA Jean</nom>
   <mail>jean.sequeira@univ-amu.fr</mail>
</intervenant>
<intervenant id="IN7722">
   <nom>NOVELLI Noel</nom>
   <mail>noel.novelli@univ-amu.fr</mail>
</intervenant>
<intervenant id="IN7779">
   <nom>THIEL Edouard</nom>
   <mail>edouard.thiel@univ-amu.fr</mail>
</intervenant>
<intervenant id="IN7931">
   <nom>RISCH Sylvie</nom>
   <mail>sylvie.risch@univ-amu.fr</mail>
</intervenant>
<intervenant id="IN8086">
   <nom>VAXES Yann</nom>
   <mail>yann.vaxes@univ-amu.fr</mail>
</intervenant>
<intervenant id="IN8416">
   <nom>MARI Jean Luc</nom>
   <mail>jean-luc.mari@univ-amu.fr</mail>
</intervenant>
<intervenant id="IN8703">
   <nom>TICHIT Laurent</nom>
   <mail>laurent.tichit@univ-amu.fr</mail>
</intervenant>
<intervenant id="IN9224">
   <nom>MORIN Remi</nom>
   <mail>remi.morin@univ-amu.fr</mail>
</intervenant>
<intervenant id="IN9941">
   <nom>BECHET Frederic</nom>
   <mail>frederic.bechet@univ-amu.fr</mail>
</intervenant>

	<parcours>
	<nom>Fiabilité et sécurité informatique (FSI)</nom>
   <responsable ref="IN2563"/>
   <description>
      <p>
         <t>La formation permet d’acquérir les principes et techniques liés à la conception, l’implémentation, l’exploitation de systèmes et applications informatiques sûrs dans un environnement ouvert et hétérogène. Les métiers visés sont ceux du large champ de la </t>
         <i>sécurité informatique</i>
         <t> (applications sécurisées, management de la sécurité, administration d’infrastructures, normes et qualité, audit de sécurité, R&amp;D)</t>
         <i>.</i>
      </p>
      <p>
         <t>La formation apporte des compétences fortes en sécurité et fiabilité des applications (web, mobiles, embarquées), en sécurité organisationnelle, en sécurité des réseaux, en hacking éthique, en protocoles et architectures cryptographiques, en méthodes formelles. L’accent est mis sur le travail en équipe, sur des projets concrets, bénéficiant de l’apport des professionnels intervenant dans la formation.</t>
      </p>
      <p>
         <t>Le parcours est labellisé </t>
         <t>SecNumEdu</t>
      </p>
      <p>
         <i>L’objectif de cette labellisation est d’apporter une assurance qualité aux étudiants et employeurs qu’une formation dans le domaine de la sécurité du numérique répond à une charte et des critères définis par l’</i>
         <i>ANSSI</i>
         <t> </t>
         <i>en collaboration avec les acteurs et professionnels du domaine (établissements d’enseignement supérieur, industriels…).</i>
      </p>
      <p>
         <b>Métiers visés</b>
         <t> :</t>
      </p>
      <ul>
         <li>
            <t>Ingénieur R&amp;D, Chargé de veille ou de recherche, Enseignant-chercheur ou chercheur</t>
         </li>
         <li>
            <t>Chef de projet</t>
         </li>
         <li>
            <t>Ingénieur études et développement</t>
         </li>
         <li>
            <t>Consultant technique ou fonctionnel</t>
         </li>
         <li>
            <t>Responsable de la sécurité des SI</t>
         </li>
         <li>
            <t>Responsable qualité</t>
         </li>
         <li>
            <t>Ingénieur test et validation</t>
         </li>
      </ul>
   </description>
   <debouche>Ingénieur Recherche et Developpement</debouche>
		<debouche>Chef de projet</debouche>
		<debouche>Ingénieur études et développement</debouche>
		<debouche>Consultant technique ou fonctionnel</debouche>
		<debouche>Responsabe de la sécurité des SI</debouche>
		<debouche>Responsable qualité</debouche>
		<debouche>Ingénieur test et validation</debouche>
   <ref-semestre ref="ME5SIN-S1"/>
   <ref-semestre ref="ME5SIN-S2"/>
   <ref-semestre ref="ME5SIN-S3FSI"/>
   <ref-semestre ref="ME5SIN-S4PRO"/>
</parcours>

<parcours>
	<nom>Ingénierie du logiciel et des données (ILD)</nom>
   <responsable ref="IN12544"/>
   <description>
      <p>
         <t>L’objectif de ce parcours est de former des informaticiens qui soient capables à la fois de travailler sur les problématiques du développement logiciel (spécification, conception, réalisation, qualité, tests, plateforme JEE et WEB) et sur les problématiques de la modélisation et du traitement de données (administration, stockage, intégration, visualisation, analyse).</t>
      </p>
      <p>
         <t>Après un tronc-commun couvrant les deux aspects, l’étudiant pourra, au travers d’options, approfondir ses connaissances sur le traitement des données (informatique décisionnelle, techniques liées au Big Data, architectures orientées données) et sur le développement (architectures logicielles et de services distribués, cloud computing, mobile, Internet des objets).</t>
      </p>
      <p>
         <t>Les diplômés réaliseront des solutions logicielles avancées dans des environnements complexes et des domaines variés pour aider les entreprises à valoriser leurs données, prendre des décisions et faciliter leur évolution vers une économie dirigée par le numérique. Ils pourront également s'orienter vers les métiers de la recherche dans les thèmes liés au parcours.</t>
      </p>
      <p>
         <b>Métiers visés</b>
         <t> :</t>
      </p>
      <ul>
         <li>
            <t>Ingénieur R&amp;D</t>
         </li>
         <li>
            <t>Chargé de veille ou de recherche, Enseignant-chercheur ou chercheur</t>
         </li>
         <li>
            <t>Chef de projet</t>
         </li>
         <li>
            <t>Ingénieur études et développement</t>
         </li>
         <li>
