=== younesyu/M1_DPR/TP/tp6/master/exemple.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ENTITY campus "Luminy">
<!ENTITY campus2 "Saint-Jerome">

<!ENTITY ueObligatoire "Obligatoire">
<!ENTITY ueOptionnelle "Option">

<!ENTITY % id 
          "id ID #REQUIRED">

<!ENTITY % ref 
          "ref IDREF #REQUIRED">

<!ELEMENT master        (intervenant*, parcours*, semestre*, unite*)>

<!ELEMENT parcours         (nom, responsable+, description, debouche*, ref-semestre*)>
<!ELEMENT responsable           EMPTY>
<!ATTLIST responsable %ref;>
<!ELEMENT debouche           (#PCDATA)>
<!ELEMENT description           (#PCDATA)>
<!ELEMENT ref-semestre EMPTY>
<!ATTLIST ref-semestre ref IDREF #REQUIRED>

<!ELEMENT semestre         (bloc-unite*) >
<!ELEMENT bloc-unite (ref-unite, role)>
<!ELEMENT ref-unite EMPTY>
<!ELEMENT role  (#PCDATA)>
<!ATTLIST ref-unite %ref;>
<!ATTLIST semestre %id;>

<!ELEMENT unite         (nom, credit, resume, plan, lieu, ref-intervenant+)>
<!ATTLIST unite %id;>
<!ELEMENT nom           (#PCDATA)>
<!ELEMENT credit        (#PCDATA)>
<!ELEMENT resume        (#PCDATA)>
<!ELEMENT plan          (chapitre*)>
<!ELEMENT lieu          (#PCDATA)>
<!ELEMENT ref-intervenant EMPTY>
<!ATTLIST ref-intervenant %ref;>

<!ELEMENT intervenant       (nom, mail, site)>
<!ATTLIST intervenant %id;>

<!ELEMENT mail      (#PCDATA)>
<!ELEMENT site      (#PCDATA)>

<!ELEMENT chapitre      (#PCDATA)>

=== younesyu/M1_DPR/TP/tp4/exemple.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE master SYSTEM "exemple.dtd">

<master>

	<intervenant id='I1'>
		<nom>Bertrand</nom>
		<mail>bertrand@sfr.fr</mail>
		<site>bertrand.fr</site>
	</intervenant>

	<intervenant id='I2'>
		<nom>Jacques</nom>
		<mail>Jacques@sfr.fr</mail>
		<site>Jacques.fr</site>
	</intervenant>

	<intervenant id='I3'>
		<nom>Henry</nom>
		<mail>henry@sfr.fr</mail>
		<site>henry.fr</site>
	</intervenant>

	<parcours>
		<responsable></responsable>
		<responsable></responsable>
		<nom></nom>
		<description></description>
		<debouche></debouche>
		<ref-semestre ref=''/>
	</parcours>

	<parcours>
		<responsable></responsable>
		<responsable></responsable>
		<nom></nom>
		<description></description>
		<debouche></debouche>
		<ref-semestre ref=''/>
	</parcours>

	<semestre id='S1'>
		<ref-unite ref='S51AN1M1' role='' />
		<ref-unite ref='S51IN1M1' role='' />
		<ref-unite ref='S51IN1M2' role='' />
		<ref-unite ref='S51IN1M3' role='' />
		<ref-unite ref='S51IN1M4' role='' />
		<ref-unite ref='S51IN1M5' role='' />
		<ref-unite ref='S51IN1M6' role='' />
		<ref-unite ref='S51PP1M2' role='' />
	</semestre>

	<semestre id='S2ILD'>
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
	</semestre>

	<semestre id='S2FSI'>
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
	</semestre>

	<semestre id='S3ILD'>
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
	</semestre>

	<semestre id='S3FSI'>
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
	</semestre>

	<unite id='UE45'>
		<nom>Données Post-Relationnelles</nom>
		<credit>6</credit>
		<resume>Blabla</resume>
		<plan>
			<chapitre>xml</chapitre>
			<chapitre>dtd</chapitre>
		</plan>
		<lieu>&campus;</lieu>
		<ref-intervenant ref='I1' />
	</unite>

	<unite id='UE46'>
		<nom>Fiabilité Logicielle</nom>
		<credit>6</credit>
		<resume>Blabla</resume>
		<plan>
			<chapitre>test Cunit</chapitre>
			<chapitre>test Junit</chapitre>
		</plan>
		<lieu>Luminy</lieu>
		<ref-intervenant ref='I2' />
		<ref-intervenant ref='I3' />
	</unite>

	<unite id='UE47'>
		<nom>Génie logiciel</nom>
		<credit>6</credit>
		<resume>
		Le génie logiciel est une science de génie industriel qui étudie les méthodes de travail et les bonnes pratiques des ingénieurs qui développent des logiciels.
		</resume>
		<plan>
			<chapitre>Versioning Git&#160;: Branches,
			Dépôts Lointains, Dépôts Lointains multiples avec branches, Workflows.</chapitre>
			<chapitre>Building Gradle&#160;: Automatisation de compilation, de tests, de 
			dépendances, langage de tâches interdépendantes.</chapitre>
			<chapitre>Méthodes Les acteurs
			du logiciel. Cycles en V. Motivation et détail de chacune des phases. 
			Forces et Faiblesses. Méthodes agiles. Motivations. Notamment XP et 
			Scrum. Détail de chacune des réunions et instruments. Forces et 
			Faiblesses. GL Libre&#160;: the cathedral and the bazaar</chapitre>
			<chapitre>Documentation Du GL&#160;: Cahier des charges, Spécifications, 
			Conception, ... Du code&#160;: Javadoc, Commentaires, Wikis, Issues 
			trackers</chapitre>
			<chapitre>UML Motivations. Tous les principaux diagrammes (classe, 
			object, séquence, com, package, états-transitions,...).</chapitre>
			<chapitre>Tests 
			Types de Test (Blanche/Noire, Intégration (continue), 
			Correction/Validation,...), Couverture (Exos sur les différents 
			critères), Quand les faire (TDD...) Découverte du debugger eclipse 
			Concepts d'invariants, d'assertions, d'analyse statique</chapitre>
			<chapitre>Estimation 
			Rapports PrixDev vs TempsDev vs LignesCode % observés de failed 
			projects, causes observées % observés de bugs</chapitre>
			<chapitre>Veille technologique 
			sur l'actualité du GL.</chapitre>
		</plan>
		<lieu>Luminy</lieu>
		<ref-intervenant ref='I2' />
		<ref-intervenant ref='I3' />
	</unite>

	<unite id='UE48'>
		<nom>Fiabilité Logicielle</nom>
		<credit>6</credit>
		<resume>Blabla</resume>
		<plan>
			<chapitre>test Cunit</chapitre>
			<chapitre>test Junit</chapitre>
		</plan>
		<lieu>Luminy</lieu>
		<ref-intervenant ref='I2' />
		<ref-intervenant ref='I3' />
	</unite>
</master>

=== younesyu/M1_DPR/exemple.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE master SYSTEM "exemple.dtd">

<master>

	<intervenant id='I1'>
		<nom>Bertrand</nom>
		<mail>bertrand@sfr.fr</mail>
		<site>bertrand.fr</site>
	</intervenant>

	<intervenant id='I2'>
		<nom>Jacques</nom>
		<mail>Jacques@sfr.fr</mail>
		<site>Jacques.fr</site>
	</intervenant>

	<intervenant id='I3'>
		<nom>Henry</nom>
		<mail>henry@sfr.fr</mail>
		<site>henry.fr</site>
	</intervenant>

	<parcours>
		<responsable></responsable>
		<responsable></responsable>
		<nom></nom>
		<description></description>
		<debouche></debouche>
		<ref-semestre ref=''/>
	</parcours>

	<parcours>
		<responsable></responsable>
		<responsable></responsable>
		<nom></nom>
		<description></description>
		<debouche></debouche>
		<ref-semestre ref=''/>
	</parcours>
	<!ELEMENT semestre         ( (ref-unite, role)* )>

	<semestre id='S1'>
		<ref-unite ref='S51AN1M1' role='' />
		<ref-unite ref='S51IN1M1' role='' />
		<ref-unite ref='S51IN1M2' role='' />
		<ref-unite ref='S51IN1M3' role='' />
		<ref-unite ref='S51IN1M4' role='' />
		<ref-unite ref='S51IN1M5' role='' />
		<ref-unite ref='S51IN1M6' role='' />
		<ref-unite ref='S51PP1M2' role='' />
	</semestre>

	<semestre id='S2ILD'>
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
	</semestre>

	<semestre id='S2FSI'>
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
	</semestre>

	<semestre id='S3ILD'>
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
	</semestre>

	<semestre id='S3FSI'>
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
		<ref-unite ref='' />
	</semestre>



	<unite id='UE45'>
		<nom>XML</nom>
		<credit>6</credit>
		<resume>Blabla</resume>
		<plan>
			<chapitre>xml</chapitre>
			<chapitre>dtd</chapitre>
		</plan>
		<lieu>&campus;</lieu>
		<ref-intervenant ref='I1' />
	</unite>

	<unite id='UE46'>
		<nom>fiabilite</nom>
		<credit>6</credit>
		<resume>Blabla</resume>
		<plan>
			<chapitre>xml</chapitre>
			<chapitre>dtd</chapitre>
		</plan>
		<lieu>Luminy</lieu>
		<ref-intervenant ref='I2' />
		<ref-intervenant ref='I3' />
	</unite>
</master>
